name: 💡 Feature request
description: Suggest a feature to improve `liquipydia`
labels: [💡 feature-request]
body:

    -   type: textarea
        id: feature-description
        attributes:
            label: Describe your suggested feature
            description: How can the project be improved?
            placeholder: |
                Example:
                  "It should work like this..."
        validations:
            required: true

    -   type: textarea
        id: use-case
        attributes:
            label: Use case
            description: Describe the problem or use case that motivates this feature.
            placeholder: |
                Example:
                  "I'm trying to do X but currently there's no way to..."
        validations:
            required: true

    -   type: textarea
        id: other-details
        attributes:
            label: Other details
            placeholder: |
                Additional details and attachments.

    -   type: checkboxes
        id: acknowledgements
        attributes:
            label: Acknowledgements
            description: Read this carefully, your issue will be closed and ignored if you skimmed through this.
            options:
                -   label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                    required: true
                -   label: I have written a short but informative title.
                    required: true
                -   label: I will fill out all of the requested information in this form.
                    required: true